- src/com/gfredericks/test/chuck/properties.clj
- test/com/gfredericks/test/chuck/properties_test.clj
When trying to generate code to destructure the results of generators
with for-all, the macro was getting caught up by gen-syms. By filtering
out symbols with the prefixes "map__" and "vec__", the macro no longer
tries to generate code that references the generated symbols and works
as expected (or at least how I expected it to work). A simple test was
added as well.
> Filtering out generated symbols

- project.clj
Instaparse 1.3.5 is not compatible with Clojure 1.7 (starting from alpha6)
> Bump instaparse version

- src/com/gfredericks/test/chuck/generators.clj
- test/com/gfredericks/test/chuck/generators_test.clj
Useful in generating varying sized map instead of always,
generating fixed map.
> Add sub-map function.

- src/com/gfredericks/test/chuck/generators.clj
- test/com/gfredericks/test/chuck/generators_test.clj
Move implementation details to test.chuck.datetimes ns
Uses gen/choose instead of gen'/bounded-int in gen-datetime, to avoid a circular dependency
Fixes #19
> Rename gen-datetime to datetime

- circle.yml
- project.clj
Without this the build fails because it hits the 4GB mem limit
> Set jvm-opts so build can run in circleCI

- test/com/gfredericks/test/chuck/clojure_test_test.clj
- test/com/gfredericks/test/chuck/exception_handling_test.clj
Make it easier to understand and debug. Leave it better prepared for migration to cljs using cljc by not using `eval` which is not available in the cljs runtime
> Refactor exception detection test

- test/com/gfredericks/test/chuck/exception_handling_test.clj
The test is currently failing, but I think we have to add a test like this not only to ensure that we detect & report exceptions correctly (as reported in #23) but also that we do the same for failures.
> Add test to verify that failures are reported correctly

- src/com/gfredericks/test/chuck/clojure_test.cljc
Update the `checking` and `for-all` macros in the `test.chuck.clojure-test`
namespace to use the `test.chuck.properties/for-all` function instead of `test.check.properties/for-all`.
Since the `test.chuck.properties/for-all` method is intended (AFAIK) to be a drop-in replacement for the vanilla `for-all`, I don't see any harm in doing this, and then the `clojure-test` functions can use all of the nice augmented functionality.
The test suite ran cleanly before and after this change, and some local testing of the new SNAPSHOT version allowed my app to correctly define a test using the enhanced `for-all` behavior in `checking`.
> Update clojure-test to use test.chuck for-all

- src/com/gfredericks/test/chuck/clojure_test.cljc
- test/com/gfredericks/test/chuck/clojure_test_output_test.cljc
- test/com/gfredericks/test/chuck/exception_handling_test.cljc
- test/com/gfredericks/test/chuck/runner.cljs
- test/com/gfredericks/test/chuck/test_utils.cljc
The checking macro was not printing the test.check result in case of
failures. This was happening since we changed the assertion on the
result of `checking` to only check if there was an exception. That
change was introduced to fix #17, which was about the output showing an
"expected: (not-falsey-or-exception? (:result result))" message. But
as a side-effect of that change, we lost the test.check result from the
output, which is very valuable.
The fix is to simply print the test.check result in case of failure.
This is part of what `do-report` would do if we called
`(is (:result result) result)` but now we avoid the other stuff that call
would do (incrementing test result counters, output the expected vs
actual result of the assertion, etc) by just calling `println`.
As a side-effect of …
> Fix missing output from tests

- test/com/gfredericks/test/chuck/clojure_test_output_test.cljc
The `:fail` and `:shrunk :smallest` entries in a failure report have changed to be a map of binding name to bound values since #30 when using `for-all` and `checking` macros.
The test clojure-test-output-test was originally written with the old output layout where it was just the vector of bound values, so this fixes it.
Fixes #31
> Fix clojure-test-output-test by tweaking the expected output

- project.clj
- test/com/gfredericks/test/chuck/generators_test.cljc
Also adds a missing `:include-macros` in `generators-test`
> Upgrade test.check to 0.9.0

- src/com/gfredericks/test/chuck/clojure_test.cljc
- test/com/gfredericks/test/chuck/clojure_test_output_test.cljc
For tools like `collection-check` it would be useful to provide some sort of hook to obtain the results of of the `quick-check` invocation that's part of the `checking` macro. 
This PR allows this extension via the regular `clojure.test/report` multimethod using namespaced keys similar to how `test.check` provides additional reporting functionality.
Adding this PR would greatly simplify the implementation of https://github.com/ztellman/collection-check/pull/13
> Extensible shrunk report

- src/com/gfredericks/test/chuck.cljc
The multiplication factor is always 1 in cljs.
> Resolves #39: Added cljs support for `times`

- src/com/gfredericks/test/chuck/generators.cljc
Avoids warnings due to calling a deprecated fn during cljs compilation.
Removes the following warning occurrences:
```
WARNING: com.gfredericks.test.chuck.generators/bounded-int is deprecated. at line 241 src/com/gfredericks/test/chuck/generators.cljc
WARNING: com.gfredericks.test.chuck.generators/bounded-int is deprecated. at line 242 src/com/gfredericks/test/chuck/generators.cljc
WARNING: com.gfredericks.test.chuck.generators/bounded-int is deprecated. at line 322 src/com/gfredericks/test/chuck/generators.cljc
```
The following warning is not removed because there's still a test for `bounded-int` in `generators-test`:
```
WARNING: com.gfredericks.test.chuck.generators/bounded-int is deprecated. at line 79 test/com/gfredericks/test/chuck/generators_test.cljc
```
> Replace calls to bounded-int with gen/large-integer*

- src/com/gfredericks/test/chuck/clojure_test.cljc
For a test like this:
```clojure
(deftest property-test
(checking
"failing test"
25
[v (gen/vector gen/string)]
(is (< (count v) 10))))
```
The message about the smallest failing case is hard to read: 
`Tests failed, smallest case: [{v [         ]}]`
By using `pr-str`, we get a more understandable message: 
`Tests failed, smallest case: [{v ["" "" "" "" "" "" "" "" "" ""]}]`
> Uses `pr-str` to ensure smallest test case is readable

- src/com/gfredericks/test/chuck/clojure_test.cljc
- test/com/gfredericks/test/chuck/clojure_test_test.cljc
Fixes https://github.com/gfredericks/test.chuck/issues/48
The `:reporter-fn` option to `quick-check` is not available on `test.check` 0.9.0, so there is no tests for it, but it should work without further modification.
To maintain backwards compatibility, I have (optionally) replaced the number of tests with a map containing all options e.g.
```clojure
(checking "less than 10" {:num-tests 11 :seed 123} [i gen/int]
(is (< i 10)))
```
This form mirrors the way you can optionally use `defspec`:
```clojure
(defspec less-than-10 {:num-tests 11 :seed 123}
(prop/for-all [i gen/int]
(< i 10)))
```
> Adds options to 'checking'

- project.clj
The version currently used (`0.3.11`) throws compiler warnings and fails at runtime (with the latest clojurescript versions at least).
> Bump com.andrewmcveigh/cljs-time version

- src/com/gfredericks/test/chuck/regexes.clj
- test/com/gfredericks/test/chuck/regexes_test.clj
What it says on the tin. I hope.
> Allow named groups in regex generation

- src/com/gfredericks/test/chuck/clojure_test.cljc
- test/com/gfredericks/test/chuck/clojure_test_output_test.cljc
- test/com/gfredericks/test/chuck/clojure_test_test.cljc
Close https://github.com/gfredericks/test.chuck/issues/57
This PR adds support for nesting `testing` inside `checking` forms and makes the options argument to `checking` optional.
> Support `testing` inside `checking` and make `checking` options optional

- resources/clj-kondo.exports/com.gfredericks/test.chuck/clj_kondo/com/gfredericks/test/chuck/checking.clj
This is a follow-up to https://github.com/gfredericks/test.chuck/pull/69.
This makes `clj-kondo` analyse `(checking` form *description* too, which makes a difference if it's not a literal, for example:
```clojure
(ns checking-test
(:require [my.ns :as some-ns-that-would-be-flagged-as-unused-without-this-change]))
...
(checking (some-ns-that-would-be-flagged-as-unused-without-this-change/myfun) 100 ...)
```
> Analyse `(checking` description in clj-kondo hook

- src/com/gfredericks/test/chuck/clojure_test.cljc
- src/com/gfredericks/test/chuck/generators.cljc
- src/com/gfredericks/test/chuck/properties.cljc
- src/com/gfredericks/test/chuck/regexes.clj
- src/com/gfredericks/test/chuck/regexes/charsets.clj
- test/com/gfredericks/test/chuck/clojure_test_output_test.cljc
- test/com/gfredericks/test/chuck/clojure_test_test.cljc
- test/com/gfredericks/test/chuck/exception_handling_test.cljc
- test/com/gfredericks/test/chuck/generators_test.cljc
- test/com/gfredericks/test/chuck/properties_test.cljc
This PR:
- adds `:require-macros` forms to each cljc namespace that includes macros. This removes the need for `:include-macros true` or `:refer-macros` for users of the library... the advantage shows in the test changes here!
- fixes most linter errors that clj-kondo revealed in the `src` directory.
> Add self-require forms, fix linter errors

- .gitignore
- deps.edn
Tested by calling `clj` in the project root and requiring a few namespaces.
> Add deps.edn

- bb.edn
- deps.edn
- src/com/gfredericks/test/chuck/generators.cljc
- src/com/gfredericks/test/chuck/generators/clj_time.cljc
- test/com/gfredericks/test/chuck/clojure_test_output_test.cljc
- test/com/gfredericks/test/chuck/generators/clj_time_test.cljc
- test/com/gfredericks/test/chuck/generators_test.cljc
Closes #82 by eliding clj-time code when running under Babashka (using the `:bb` reader conditional) and the instaparse pod. Adding the instaparse-bb dep doesn't affect JVM CLJ nor CLJS environments as that library only contains `.bb` files.
> Babashka compatibility

- .github/workflows/test.yml
- README.md
- deps.edn
This version contains the final fixes that allow this to work under Babashka (and its test suite to run and pass).
It still requires a master HEAD build of Babashka itself, so not _quite_ ready for prime time, but this should be the final change needed in here for the basic functionality.
> Bump instaparse-bb version to v0.0.6
